### ISSUE TITLE
Cambio de diseño 

### ISSUE THREAD

**Issue by elias-miguel-vergara** [elias-miguel-vergara/mejoras-questionarie#21]
Descripción:

Queremos actualizar el diseño del cuestionario alojado en el siguiente enlace: https://saikilito.github.io/quetionnaire/. Se solicita implementar cambios que incluyan:
Cambios de Color: Actualizar la paleta de colores para que sea más atractiva y acorde con la imagen de nuestra marca. Los colores sugeridos son [proporcionar los colores deseados aquí].Estilo Mejorado: Utilizar estilos modernos y atractivos para mejorar la apariencia visual del cuestionario.
Animaciones: Agregar animaciones sutiles pero efectivas para mejorar la experiencia del usuario y hacer que la interfaz sea más dinámica.Recursos Adicionales:Se proporcionará acceso al código fuente del cuestionario para realizar los cambios necesarios.

**Comment by Israel-Laguan** [comment]
Este creo que lo bloquea #22

**Comment by elias-miguel-vergara** [comment]
Cerrar
