### ISSUE TITLE
Ticket de Mejoras del Backend - Parte 1: Optimización de Consultas y Refactorización de Código

### ISSUE THREAD

**Issue by elias-miguel-vergara** [elias-miguel-vergara/mejoras-questionarie#3]
Descripción:El propósito de esta parte del ticket es abordar la optimización de consultas a la base de datos y refactorizar el código existente para mejorar la eficiencia y la mantenibilidad del backend.

Tareas Propuestas:Análisis de Consultas SQL:Realizar un análisis exhaustivo de todas las consultas SQL utilizadas en el proyecto para identificar aquellas que puedan estar afectando negativamente el rendimiento.Documentar las consultas identificadas, incluyendo el tiempo de ejecución, el número de filas afectadas y cualquier posible optimización.

**Comment by Israel-Laguan** [comment]
NO hay backend, creo que deberia cerrarse
