### ISSUE TITLE
Ticket de Mejoras del Backend - Parte 1: Optimización de Consultas y Refactorización de Código tarea #4

### ISSUE THREAD

**Issue by elias-miguel-vergara** [elias-miguel-vergara/mejoras-questionarie#6]
Refactorización del Código:

Realizar una revisión exhaustiva del código existente para identificar áreas que puedan beneficiarse de la refactorización.
Refactorizar el código para mejorar su legibilidad, modularidad y mantenibilidad, eliminando código duplicado y consolidando funciones similares

**Comment by jsha64** [comment]
**AVANCE DE HOY (23/03/2024)**
Se hizo una brebe correcion de sintaxis y reorganizacion codigo.

**Comment by jsha64** [comment]
- [ ] Ticket Terminado

**Comment by jsha64** [comment]
- [ ] 

> Ticket Terminado

**Comment by jsha64** [comment]
- [x] **Ticket Terminado**
