### ISSUE TITLE
1: Optimización de Consultas y Refactorización de Código tarea #6

### ISSUE THREAD

**Issue by elias-miguel-vergara** [elias-miguel-vergara/mejoras-questionarie#8]
Documentación de Cambios:

Documentar todas las optimizaciones realizadas en las consultas y el código en un lugar centralizado, como el archivo README o la documentación técnica del proyecto.Incluir detalles sobre los cambios específicos realizados y los beneficios esperados en términos de rendimiento y mantenibilidad.

**Comment by Israel-Laguan** [comment]
Esto deberia ser parte de #6 y se cierra esta

**Comment by elias-miguel-vergara** [comment]
Cerrar
